version: "3.7"

services:
  travas-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app

  travas-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    # command: /app/travasAPI --flag1 --flag2
    # image: ayaa001/travas-server:latest
    # container_name: ayaa001/travas-server:latest

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    restart: always
